/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SXOI3vHP0zd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Hero() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-gray-100 dark:bg-gray-950">
      <div className="mx-4 grid w-full max-w-md gap-6 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-900 sm:p-8">
        <div className="space-y-2 text-center">
          <h1 className="text-2xl font-bold">URL Shortener</h1>
          <p className="text-gray-500 dark:text-gray-400">Shorten your long URLs with ease.</p>
        </div>
        <form className="grid gap-4">
          <div>
            <Label className="text-sm font-medium" htmlFor="url">
              Long URL
            </Label>
            <Input className="mt-1" id="url" placeholder="https://example.com/very-long-url" type="url" />
          </div>
          <Button type="submit">Shorten URL</Button>
        </form>
        <div className="space-y-2">
          <h2 className="text-lg font-medium">Shortened URL</h2>
          <div className="flex items-center space-x-2">
            <Input className="flex-1 bg-gray-100 dark:bg-gray-800" readOnly value="https://example.com/abc123" />
            <Button size="sm" variant="outline">
              Copy
            </Button>
          </div>
        </div>
      </div>
      <div className="hidden h-full w-64 border-l bg-gray-100 p-6 dark:bg-gray-950 md:block">
        <div className="space-y-4">
          <h2 className="text-lg font-medium">Previous URLs</h2>
          <div className="space-y-2">
            <div className="flex items-center justify-between rounded-md bg-white p-2 shadow-sm dark:bg-gray-900">
              <div className="truncate text-sm font-medium text-gray-900 dark:text-gray-50">
                https://example.com/very-long-url-that-needs-shortening
              </div>
              <Button size="sm" variant="outline">
                Copy
              </Button>
            </div>
            <div className="flex items-center justify-between rounded-md bg-white p-2 shadow-sm dark:bg-gray-900">
              <div className="truncate text-sm font-medium text-gray-900 dark:text-gray-50">
                https://example.com/another-long-url
              </div>
              <Button size="sm" variant="outline">
                Copy
              </Button>
            </div>
            <div className="flex items-center justify-between rounded-md bg-white p-2 shadow-sm dark:bg-gray-900">
              <div className="truncate text-sm font-medium text-gray-900 dark:text-gray-50">
                https://example.com/this-one-is-also-long
              </div>
              <Button size="sm" variant="outline">
                Copy
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
